spring.application.name=integration-camunda

# Camunda 8 SaaS credentials
zeebe.client.cloud.cluster-id=c3d21e30-e803-467a-9dae-bce651b43d54
zeebe.client.cloud.client-id=Tw~RozutFvDsiDTjmZ30u57aoPALSNKd
zeebe.client.cloud.client-secret=z9WxO.OomKGYP8r~LAl~_7yIzLC~s.6kK.HMmShnfi1z~QZTMbB03u4c5uoC3yb.
zeebe.client.cloud.region=sin-2

# Log
logging.level.io.camunda=INFO
logging.level.com.example.demo=DEBUG
